apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: agent-service
  name: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: agent-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              value: airbnb_db
            - name: DB_PORT
              value: "27017"
            - name: OLLAMA_HOST
              value: ollama
            - name: OLLAMA_PORT
              value: "11434"
          image: airbnb_prototype-agent-service
          imagePullPolicy: IfNotPresent
          name: agent-service-container
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: agent-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: agent-service-cm0
          name: agent-service-cm0
