apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              value: airbnb_db
            - name: DB_PORT
              value: "27017"
            - name: FRONTEND_URL
              value: http://localhost:3000
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "5001"
            - name: SESSION_SECRET
              value: auth-service-secret
          image: airbnb_prototype-auth-service
          imagePullPolicy: IfNotPresent
          name: auth-service-container
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
      volumes:
        - configMap:
            name: auth-service-cm0
          name: auth-service-cm0
        - name: auth-service-claim1
          persistentVolumeClaim:
            claimName: auth-service-claim1
