apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: property-service
  name: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: property-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: property-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              value: airbnb_db
            - name: DB_PORT
              value: "27017"
            - name: FRONTEND_URL
              value: http://localhost:3000
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "5002"
            - name: SESSION_SECRET
              value: property-service-secret
          image: airbnb_prototype-property-service
          imagePullPolicy: IfNotPresent
          name: property-service-container
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /app/uploads/properties
              name: property-service-cm2
      restartPolicy: Always
      volumes:
        - configMap:
            name: property-service-cm0
          name: property-service-cm0
        - name: property-service-claim1
          persistentVolumeClaim:
            claimName: property-service-claim1
        - configMap:
            name: property-service-cm2
          name: property-service-cm2
