apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  namespace: airbnb
data:
  NODE_ENV: "production"
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "airbnb_db"
  KAFKA_BROKER: "kafka-service:9092"
  FRONTEND_URL: "http://localhost:3000"